# docker-compose file
version: '3.8'

services:
  student:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: student
    platform: linux/amd64
    container_name: student
    image: student:latest
    ports:
      - 8000:8000
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    container_name: postgres
    hostname: postgres
    platform: linux/amd64
    environment:
      POSTGRES_DB: local_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - .:/data